create table bakery_item (id integer generated by default as identity, ingredients varchar(255), price double, timestamp timestamp, primary key (id))
create table customer (id integer generated by default as identity, address varchar(255), name varchar(255), phone_number varchar(255), primary key (id))
create table order (id integer not null, bakery_itemid integer, order_dateid integer, primary key (id))
create table order_date (id integer generated by default as identity, order_date timestamp, requested_date timestamp, primary key (id))
